apiVersion: v1
kind: Namespace
metadata:
  name: dev

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodejs-ingress
  namespace: dev
spec:
  rules:
  - host: samalya.creativity.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: node-react-service
          servicePort: 80