# Sample Test
name: Run python code 

on: [workflow_dispatch]  

jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        python-version: [3.8, 3.9]
        
    
    steps:
    - name: Checkout Source Code
      uses: .github/actions/checkout@v1
      with:
       repository: ${{ inputs.repository }}
       ref: ${{ inputs.branch }}
       
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install requests

    - name: Run Source code
      run: |
        #cd actions
        python .github/actions/apicall.py
