# Sample Test
name: Run python code 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/set-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Source code
      run: |
        cd python
        python rest_api_cal.py
